apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod-2
spec:
  containers:
  - name: my-gpu-container
    image: gcr.io/deeplearning-platform-release/base-cu110
#    command: ["/bin/bash", "-c", "--"]
    command: ["tail", "-f", "/dev/null"]
#    args: ["nvidia-smi"]
    resources:
      limits:
       nvidia.com/gpu: 4